name: Stylesheet Lint
on: [push, pull_request]

jobs:
    linters:
        name: stylelint
        runs-on: ubuntu-latest
      
        steps:
            - uses: actions/checkout@v1
            - uses: actions-hub/stylelint@master
            - uses: actions-hub/stylelint/post-css-in-js